package:
  name: obinding
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  - numpy
  - pyunitwizard
  - pandas
  - openmm
  - molsysmt
  - nglview
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This toolkit library provides some useful classes, functions, pipes
    and wrappers daily used in the uibcdf lab to work with molecular systems.

    '
  dev_url: https://github.com/uibcdf/OBinding
  doc_url: https://uibcdf.org/OBinding
